### ISSUE TITLE
no-collision and spawn-location are not working correctly

### ISSUE THREAD

**Issue by IasonKalaitzakis** [marlester-dev/ReallyFakePlayers#10]
Enabled no collision and the players still have collision. 
Changed the spawn point away from 0, 0 and it remained there.

**Comment by IasonKalaitzakis** [comment]
Oh also a minor thing but the reload command doesn't seem to reload the config correctly.

**Comment by marlester-dev** [comment]
Hello, for the spawn location please use the `/rfp setspawn` command (sets fake players' spawn location at your location).
Improperly working `no-collision` is a bug, so I will investigate that. Also, please do not use the `/reload` command, instead use `/rfp reload` or restart the server.

**Comment by IasonKalaitzakis** [comment]
I did use /rfp setspawn and it is getting ignored (coords show up on the config, but players don't spawn there). And my bad on my wording, I meant the /rfp reload command isn't working correctly.

**Comment by marlester-dev** [comment]
> I did use /rfp setspawn and it is getting ignored (coords show up on the config, but players don't spawn there). And my bad on my wording, I meant the /rfp reload command isn't working correctly.

I can't reproduce your issue with spawn location not working. Do you use any plugins that change players' spawn location?
How is /rfp reload not working correctly? I need more details.

**Comment by marlester-dev** [comment]
I've identified an issue from the plugin's side, because the plugin gets loaded on early startup (when the world is not yet loaded), the config gets loaded and it doesn't recognize the location because no worlds are loaded yet, and throws an error. I will fix that.
But I gotta warn you that a lot of SetSpawn plugins are incompatible with this plugin, instead of properly using  PlayerSpawnLocationEvent, they just teleport the player on PlayerJoinEvent which is bad.

**Comment by marlester-dev** [comment]
I have a temporary solution for you (for the spawn location, untill I release the fixed version):
Open plugin's jar with WinRar, modify plugin.yml:
load: STARTUP -> load: POSTWORLD

And in config.yml:
in join-commands.as-console add a command teleporting the fake player to the desired location. It Should work.

**Comment by marlester-dev** [comment]
Sadly, I can't fix the no-collision thing, it's connected with client side somehow. Even though fake players don't get collided, clients of players still force themselves to move.

**Comment by IasonKalaitzakis** [comment]
> > I did use /rfp setspawn and it is getting ignored (coords show up on the config, but players don't spawn there). And my bad on my wording, I meant the /rfp reload command isn't working correctly.
> 
> I can't reproduce your issue with spawn location not working. Do you use any plugins that change players' spawn location? How is /rfp reload not working correctly? I need more details.

After some testing, I may have been wrong in thinking the command isn't working, but rather the config is defaulting to something it shouldn't, if the specific field of the 

join-commands:
  \# You are able to unset this to disable this
  as-console:

is cleared. It was making the server run the "say greetings player" command (that you originally have as an example) even though I had cleared it and saved and reloaded. Using another command instead of leaving it empty fixed it.

**Comment by marlester-dev** [comment]
> > > I did use /rfp setspawn and it is getting ignored (coords show up on the config, but players don't spawn there). And my bad on my wording, I meant the /rfp reload command isn't working correctly.
> > 
> > 
> > I can't reproduce your issue with spawn location not working. Do you use any plugins that change players' spawn location? How is /rfp reload not working correctly? I need more details.
> 
> After some testing, I may have been wrong in thinking the command isn't working, but rather the config is defaulting to something it shouldn't, if the specific field of the
> 
> join-commands: # You are able to unset this to disable this as-console:
> 
> is cleared. It was making the server run the "say greetings player" command (that you originally have as an example) even though I had cleared it and saved and reloaded. Using another command instead of leaving it empty fixed it.

I fixed that bug. Now you can unset it properly. The new version will be available soon on BukkitDev. (tomorrow or so)
