### ISSUE TITLE
Request: Include configurable chance % to not reply to new or returning players

### ISSUE THREAD

**Issue by IasonKalaitzakis** [marlester-dev/ReallyFakePlayers#11]
Not sure if this is already possible with blank messages, since it is a bit hard to test. Would also appreciate some safeguard to prevent spamming wbs to a lagging player that keeps leaving and rejoining :)

**Comment by marlester-dev** [comment]
Now we've just got to wait till CurseForge approves the new version. I'm going to be honest, the approval times are not very impressing.

**Comment by IasonKalaitzakis** [comment]
> Now we've just got to wait till CurseForge approves the new version. I'm going to be honest, the approval times are not very impressing.

Not sure on the benefits of each platform, but maybe that is the reason that most big plugins are instead hosted on spigotmc.org? Regardless, thanks for the fast responses and adding the feature <3

**Comment by marlester-dev** [comment]
> > Now we've just got to wait till CurseForge approves the new version. I'm going to be honest, the approval times are not very impressing.
> 
> Not sure on the benefits of each platform, but maybe that is the reason that most big plugins are instead hosted on spigotmc.org? Regardless, thanks for the fast responses and adding the feature <3


If I hosted on spigotmc.org, I'd have to make the plugin cost money in order to get some profit.

**Comment by marlester-dev** [comment]
And the modrinth rejected my plugin. That's why I have to stay on CurseForge (BukkitDev).
