### ISSUE TITLE
Fake players can't join server that enforces recource pack.

### ISSUE THREAD

**Issue by stelioshah** [marlester-dev/ReallyFakePlayers#16]
Hey, this plugin is amazing but on my server I am facing the issue above. There is a server configuration that enforces players to accept a resource pack on player join or they leave the server (this is a normal server configuration not something extra). I suppose that this is the reason that the bots are unable to join my server. Would there be an easy fix for this? When a player joins the server for the very first time, a screen pops up that asks whether or not they would like to accept the resource pack or leave the server.

**Comment by stelioshah** [comment]
They can't get past this screen:

![image](https://github.com/marlester-dev/ReallyFakePlayers/assets/12964902/6c675d36-ace6-4976-919d-1ed8e4e4a689)


Console:

`[15:18:51 INFO]: UUID of player full5 is c9b6dbf4-7a95-31d6-9dab-0c1acff5fe29
[15:19:20 ERROR]: [ReallyFakePlayers] Fake player full5 doesn't seem to show any life signs after ~30 seconds, meaning he didn't join/quit correctly! Aborting!`

**Comment by stelioshah** [comment]
Hey, thanks again for the work. I checked your code and saw that you fixed this with packets. I just tested this in a brand new paper 1.20.4 server but I have been getting the exact same issue. I am probably doing something wrong. I had also attempted to fix the issue externally using packets but I failed miserably. How did you test your fix, so that I can replicate it? Thanks again.

```
[22:47:00 ERROR]: [ReallyFakePlayers] Fake player Duy doesn't seem to show any life signs after ~30 seconds, meaning he didn't join/quit correctly! Aborting!
[22:47:00 INFO]: com.mojang.authlib.GameProfile@56d4251c[id=0f5e61eb-ab4a-3e51-b1b6-55d7d99a6aac,name=Duy,properties={}] lost connection: Disconnected`
```

EDIT: I am probably doing something wrong providing an appropriate resource-pack-id (based on the code I am seeing). But even after providing a random UUID, bots are still unable to join.

EDIT2: I actually also tried specifying an id for my resource pack in the pack.mcmeta and then using said id in the server properties but it still didn't work.

**Comment by marlester-dev** [comment]
> Hey, thanks again for the work. I checked your code and saw that you fixed this with packets. I just tested this in a brand new paper 1.20.4 server but I have been getting the exact same issue. I am probably doing something wrong. I had also attempted to fix the issue externally using packets but I failed miserably. How did you test your fix, so that I can replicate it? Thanks again.
> 
> ```
> [22:47:00 ERROR]: [ReallyFakePlayers] Fake player Duy doesn't seem to show any life signs after ~30 seconds, meaning he didn't join/quit correctly! Aborting!
> [22:47:00 INFO]: com.mojang.authlib.GameProfile@56d4251c[id=0f5e61eb-ab4a-3e51-b1b6-55d7d99a6aac,name=Duy,properties={}] lost connection: Disconnected`
> ```
> 
> EDIT: I am probably doing something wrong providing an appropriate resource-pack-id (based on the code I am seeing). But even after providing a random UUID, bots are still unable to join.
> 
> EDIT2: I actually also tried specifying an id for my resource pack in the pack.mcmeta and then using said id in the server properties but it still didn't work.

The last release (3.0.5) doesn't have the fix yet. Did you compile the plugin?

**Comment by marlester-dev** [comment]
I send you the new release: https://dropmefiles.com/82usD. Try it, it should work.

**Comment by marlester-dev** [comment]
Oh and the password there is mnAw3e

**Comment by marlester-dev** [comment]
it should get approved on curseforge today, but they have big delays

**Comment by stelioshah** [comment]
Oh sorry I thought that the fix was on the last release as well! I didn't try to compile it. Thanks!
