### ISSUE TITLE
add anti afk measure or option

### ISSUE THREAD

**Issue by kingakis2** [marlester-dev/ReallyFakePlayers#24]
it will be great if the fake players can meaby move randomly or something like this so they don't get afk status automatically

**Comment by Deaziii** [comment]
All you need to do is create a group and add anti-AFK rights from another plugin there.

Add this group to the fakes plugin

**Comment by kingakis2** [comment]
hey i didn't think about that, thanks for the answer

**Comment by marlester-dev** [comment]
> hey i didn't think about that, thanks for the answer

Did it work out?
