### ISSUE TITLE
Add randomized ping

### ISSUE THREAD

**Issue by IasonKalaitzakis** [marlester-dev/ReallyFakePlayers#25]
Many non-vanilla clients like Feather show each players ping numerically in tab. All fake players show 0 ping. Would be nice if there was a randomized ping number (if that is possible).

**Comment by marlester-dev** [comment]
Implementing this feature is not a simple task, as I attempted to do so once and have been unsuccessful.
There is a feature in NEZNAMY's TAB plugin (not my plugin) to hide the ping though, it was discussed on reddit: https://www.reddit.com/r/admincraft/comments/1ap6st3/a_way_to_hide_a_players_pingms_like_hypixel/
