### ISSUE TITLE
Multi Spawn Points

### ISSUE THREAD

**Issue by Krazytrain** [marlester-dev/ReallyFakePlayers#27]
Allow to have multi spawn points you can set. If you have more then 25 in a single spot your server TPS drops.

**Comment by marlester-dev** [comment]
Unlikely to be implemented, because it is superfluity. As a workaround, you could force fakeplayers to execute the /rtp command in config.

**Comment by marlester-dev** [comment]
Or you could teleport them to a command block that teleports them somewhere else with a mechanism. Just be creative.
