### ISSUE TITLE
MC 1.21

### ISSUE THREAD

**Issue by LudovicoPletto** [marlester-dev/ReallyFakePlayers#37]
Can you please update the plugin to support 1.21?

**Comment by marlester-dev** [comment]
Yes, of course, it's planed in approximately 20 days.
Cheers 🙂

**Comment by LudovicoPletto** [comment]
ok thanks

**Comment by marlester-dev** [comment]
@Ludovix2812 it's out: https://dev.bukkit.org/projects/really-fake-players/files/5597045
please read the changelog because of miniplaceholders 2.3.0
