### ISSUE TITLE
Cmi and rfp conflict

### ISSUE THREAD

**Issue by SemperAmici** [marlester-dev/ReallyFakePlayers#40]
Using CMI Setfirstspawn command for new players to log into my spawn it overrides the rfps spawn location causing the fake players to spawn like regular new players.

**Comment by marlester-dev** [comment]
Hello, I will test it

**Comment by marlester-dev** [comment]
Hi, CMI is not open-source, so I can't fix it. But it seems definitely not to be the fault of ReallyFakePlayers, because we have the highest event priority, which means, that no other plugin should override it.
As alternative for CMI I recommend [EssentialsX](https://essentialsx.net/downloads.html)
