### ISSUE TITLE
Dependecies Not Updated

### ISSUE THREAD

**Issue by LudovicoPletto** [marlester-dev/ReallyFakePlayers#41]
Hi, i'll make an example. When you will update the plugin for 1.21.1 the dependecies (which is MiniPlaceHolders) will still be not updated. So, does the plugin work without it? Or we have to wait for the other plugin to update? Because the 1.21 for MiniPlaceHolders it isn't even come out yet.

**Comment by marlester-dev** [comment]
Hello, please use a miniplaceholders snapshot

**Comment by marlester-dev** [comment]
when it's outdated, try MiniPlaceholders [dev-builds](https://github.com/MiniPlaceholders/MiniPlaceholders/actions)
