### ISSUE TITLE
compatible with VentureChat

### ISSUE THREAD

**Issue by xinge4088** [marlester-dev/ReallyFakePlayers#42]
Is it possible to be compatible with VentureChat? Otherwise, if fakeplyer speak, it will be exposed. I have changed the chat display format, but fake players still chat in the original format.

**Comment by marlester-dev** [comment]
Hello, it seems to be the VentureChat's fault, so I won't fix this. They seem to not support essential Paper Events and Bukkit Methods like player#chat and AsyncChatEvent.
As alternative to VentureChat I recommend EssentialsXChat
