### ISSUE TITLE
Error occurred while enabling RFP v4.0.3

### ISSUE THREAD

**Issue by Malythist** [marlester-dev/ReallyFakePlayers#45]
Environment:
Paper 1.21
RFP v4.0.3
MiniPlaceholders 2.2.4
![image](https://github.com/user-attachments/assets/028721b2-7206-40f8-a81b-d7f874509a04)

**Comment by marlester-dev** [comment]
Уважаемый Егор Гроцкий,

MiniPlaceholders 2.2.4 не совместим с версией Minecraft 1.21. Я прошу вас установить MiniPlaceholders 3.0.0 snapshot, чтобы устранить эту проблему. Он еще не опубликован на Modrinth, поэтому его нужно будет скачать с GitHub Actions: https://github.com/MiniPlaceholders/MiniPlaceholders/actions/runs/10541732294/artifacts/1850819801.

С уважением,
Марлестер
