### ISSUE TITLE
Feature Request: Paper 1.20.2 support

### ISSUE THREAD

**Issue by quiquelhappy** [marlester-dev/ReallyFakePlayers#8]
### Is your feature request related to a problem? Please describe.

The plugin does not work on 1.20.2

### Describe the solution you'd like

Use Spigot's api or paper

### Describe alternatives you've considered

None

### Checklist.

- [X] I confirm that there are no similar issues.
- [ ] I ticked all of the boxes without actually reading them.

**Comment by marlester-dev** [comment]
Hello, this is going to be implemented in the rewrite, however if 1.20.3 comes out soon, 1.20.2 may be skipped.

**Comment by bobhenl** [comment]
Any ETA for the release, please?

**Comment by marlester-dev** [comment]
> Any ETA for the release, please? 

Thanks for reminding me. I've done most of the code, but sadly lost time and motivation at the very end. I'll try to finish it some day of January/February 2024.

**Comment by IasonKalaitzakis** [comment]
Aw was hoping for a December release :(

**Comment by marlester-dev** [comment]
> Aw was hoping for a December release :(

I have good news, thankfully I got time and motivation now, therefore the first alpha may even appear in December. Thank you for your patience.

**Comment by IasonKalaitzakis** [comment]
> > Aw was hoping for a December release :(
> 
> I have good news, thankfully I got time and motivation now, therefore the first alpha may even appear in December. Thank you for your patience.

woo :)

**Comment by bobhenl** [comment]
> > Aw was hoping for a December release :(
> 
> I have good news, thankfully I got time and motivation now, therefore the first alpha may even appear in December. Thank you for your patience.

Amazing!

**Comment by marlester-dev** [comment]
Dear @quiquelhappy , @bobhenl and @IasonasKalaitzakis ,

v3.0.0 for minecraft 1.20.4 is just coming out! It'll be available as soon as CurseForge approves it.
Thank you for your patience.

**Comment by marlester-dev** [comment]
~~Just so you know, the approval by CurseForge may take longer, in the meanwhile I leave it here for you:~~

**Comment by marlester-dev** [comment]
Just got approved! Check it out here: https://dev.bukkit.org/projects/really-fake-players/files/5017928
